apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: demo-app-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cicd
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: cicd/production
        property: PGDATABASE
    - secretKey: POSTGRES_USER
      remoteRef:
        key: cicd/production
        property: PGUSER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: cicd/production
        property: PGPASSWORD
