apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-demo-app
  namespace: demo-app-prod
spec:
  ingressClassName: traefik

  rules:
    - host: cicd-demo-prod.192.168.8.121.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cicd-demo-app
                port:
                  number: 80
