apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-app-staging
type: Opaque
stringData:
  POSTGRES_USER: cicd_staging_user
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: cicd_staging
  
