apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-app-prod
type: Opaque
stringData:
  POSTGRES_USER: cicd_production_user
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: cicd_production
