# Initial config
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-app-prod
type: Opaque

stringData:
  DB_NAME: <PRODUCTION_DB_NAME>
  DB_USER: <PRODUCTION_DB_USER>
  DB_PASSWORD: <PRODUCTION_DB_PASSWORD>
